#!/usr/bin/env bash

##############################################################################
# Copies the environmental variables template file to the project root folder.
##############################################################################

# This file's directory
CURRENT_DIR="$( builtin cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT_DIR="${CURRENT_DIR}/.."

cp "${PROJECT_ROOT_DIR}/.env.template" "${PROJECT_ROOT_DIR}/.env"
