#!/usr/bin/env bash

# This file's directory
CURRENT_DIR="$( builtin cd -P "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT_DIR="${CURRENT_DIR}/.."

DATABASE_NAME="letsmeet"

echo "Dropping letsmeet database..."
dropdb --if-exists "${DATABASE_NAME}"

echo "Creating letsmeet database..."
createdb "${DATABASE_NAME}"

echo "Creating types and tables..."
psql letsmeet -f "${PROJECT_ROOT_DIR}/database/create_gender_identities_type.sql"
psql letsmeet -f "${PROJECT_ROOT_DIR}/database/create_users_and_profiles_tables.sql"
psql letsmeet -f "${PROJECT_ROOT_DIR}/database/create_activation_tokens_table.sql"
psql letsmeet -f "${PROJECT_ROOT_DIR}/database/create_user_settings_table.sql"

echo "Done!"

exit 0
